### ISSUE TITLE
Quotes in sudo commands should be escaped

### ISSUE THREAD

**Issue by mik01aj** [pstadler/flightplan#99]
In my flightplan, when I do:

    remote.sudo('node -e \'console.log("hello")\'', {user: 'blabla'})

I get an error:

```
remote $ sudo -u blabla -i bash -c 'node -e 'console.log("hello")''
remote > bash: -c: line 0: syntax error near unexpected token `('
remote > bash: -c: line 0: `sudo -u blabla -i bash -c 'node -e 'console.log("hello")'''
```

The same command (`node -e 'console.log("hello")'`), when I try it in bash is valid and works fine.

**Comment by mik01aj** [comment]
This is actually surprisingly hard. Bash sucks...

http://stackoverflow.com/questions/1250079/how-to-escape-single-quotes-within-single-quoted-strings

**Comment by pstadler** [comment]
This is indeed rather hard. I wrote quite a lot of shell scripts, maybe I can tackle this at some point.

**Comment by zxqfox** [comment]
This would be enough:
```js
function escapeShellArg (cmd) {
    return '\'' + cmd.replace(/\'/g, "'\\''") + '\'';
}
```

**Comment by pstadler** [comment]
@zxqfox this seems to be the correct solution indeed. Will try to get a new release ready soon.

**Comment by cmckendry** [comment]
It looks like the fix for this (specifically the removal of the -c flag) has introduced an error in a portion of our deployment process that uses the sudo functionality to run "chown" on the remote machine. Code is as follows:

`remote.sudo("chown -R nobody:nobody " + rootDir + "/application/config/", {user: sudoUser});`

In 0.6.4 this works as expected. In 0.6.5 it fails with a `No such file or directory` error. Is there a change to the format that needs to be made on our side in order to support the new sudo method?

**Comment by pstadler** [comment]
Hey @cmckendry what's `rootDir`. I suspect it breaks because you're using a relative path?

**Comment by pstadler** [comment]
I could verify the error, please ugprade to 0.6.6 which reverts the sudo command to the old behavior.

Thanks for reporting.

**Comment by pstadler** [comment]
@cmckendry :beers: https://github.com/pstadler/flightplan/releases/tag/0.6.6

**Comment by cmckendry** [comment]
Confirmed, that fixed it. Thanks!
